# Ansible Inventory — defines which servers to manage
# Update IPs after each terraform apply

[bastion]
bastion_server ansible_host=<your-bastion-public-ip> ansible_user=opc ansible_ssh_private_key_file=~/.ssh/oci-federal-lab/<your-bastion-ssh-key>.key

[app]
app-server ansible_host=10.0.2.201 ansible_user=opc ansible_ssh_private_key_file=~/.ssh/oci-federal-lab/<your-appserver-ssh-key>.key

[app:vars]
# App servers are in a private subnet — connect through bastion
ansible_ssh_common_args='-o ProxyCommand="ssh -i /home/<your-windows-username>/.ssh/oci-federal-lab/<your-bastion-ssh-key>.key -W %h:%p opc@<your-bastion-public-ip>"'
ansible_python_interpreter=/usr/bin/python3
